In [1]:
import numpy as np

    Crating Arrays
Los arrays son la base de NumPy: estructuras similares a listas de Python, pero mucho más rápidas y eficientes para operaciones matemáticas y científicas.

Formas de crear arrays:

In [7]:
#Desde una lista de Python
a = np.array([1, 2, 3])
print(a)

print() #espacio

#Desde una matriz (lista de listas)
b = np.array([(1,2), (3,4)])
print(b)

[1 2 3]

[[1 2]
 [3 4]]


    Initial Placeholders (Plantillas)
Sirven para crear arrys inicializados sin tener que definir manualmente cada número.

In [ ]:
c = np.arange(0, 10, 3) #Valores de 0 a 10 avanzando de 3 en 3
print(c)
print()
d = np.linspace(0, 1, 5) # 5 valores entre 0 y 1
print(d)
print()
e = np.zeros((3,4)) #Crea una matriz 3x4 de puros 0 (float)
print(e)
print()
f = np.ones((3,3), dtype=np.int16) #Crea una matriz 3x3 de puros 1 (interger)
print(f)
print()
g = np.full((2,6), 7) #Crea una matriz 2x6 de puros 
print(g)
print()
h = np.eye(3) #Crea una matriz identidad de 3x3
print(h)
print()
i = np.empty((3,2)) #Crea una mtriz 3x2 vacía (valores aleatorios en memoria)
print(i)

[0 3 6 9]

[0.   0.25 0.5  0.75 1.  ]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1.57072500e-311 1.57072500e-311]
 [1.57072500e-311 0.00000000e+000]
 [1.29441743e-312 9.76154329e-313]]


    Input/Output
NumPy puede guardar y cargar arrays directamente desde disco, lo que es útil para proyectos grandes.

Saving on Disk
Guardan datos en binario, manteniendo el tipo ¿, forma y precisión del array.
Es más rápido y eficiente que guaradar en archivos de texto.

In [31]:
arr = np.arange(10)

#Guardar un solo array
np.save('data.npy', arr)

#Cargar el array
load_arr = np.load('data.npy')
print(load_arr)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Guardar múltiples arrays
np.savez('data.npz', array1=arr1, array2=arr2)

# Cargar
data = np.load('data.npz')
print(data['array1'])
print(data['array2'])

[1 2 3]
[4 5 6]
