CONVERTIR IMÁGENES A ARRAYAS NUMPY

Cuando cargas una imagen con OpenCV se convierte automáticamente en un array Numpy 3D (alto, ancho, canales)

In [100]:
import cv2
import numpy as np

img = cv2.imread("../sources/foto.png") #Cargar imagen como array
print(type(img))  # Tipo de dato: <class 'numpy.ndarray'>
print(img.shape)  # (altura, ancho, canales)

<class 'numpy.ndarray'>
(2475, 4400, 3)


In [94]:
#Verifica que la imagen se haya cargado
if img is None:
    print("La imagen No se encpntró")
else:
    print("Forma de la imagen:", img.shape)

Forma de la imagen: (2475, 4400, 3)


In [98]:
#Recortar una región de la imagen (slicing)
alto, ancho = img.shape[:2]

#Recortar la zona central
recorte = img[alto//4: 3*alto//4, ancho//4: 3*ancho//4]

#Muestra el recorte
cv2.imshow("Recorte", recorte)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [101]:
#Cpnvertir la imagen a escala de grises
gris = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#Muestra el la imagen en gris
cv2.imshow("Gris", gris)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [55]:
#Array de 1D con números del 0 al 9
arr1D = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1D)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
#Crea una matriz 3x3 de ceros
matrix3x3 = np.zeros((3,3), dtype=int)
print(matrix3x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [57]:
# Cambia el valor del centro por 9
matrix3x3[1,1] = 9
print(matrix3x3)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [58]:
#Crea una matriz 4x4 con números aleatorios entre 0 y 9
matrix4x4 = (np.random.rand(4,4) * 10).astype(int)
print(matrix4x4)

[[9 7 8 7]
 [8 6 3 0]
 [5 7 1 6]
 [9 5 4 7]]


In [59]:
#Suma dos matrices del mismo tamaño
matriz1 = np.array([[1,2],
                   [3,4]])

matriz2 = np.array([[5,6],
                   [8,9]])

suma = matriz1 + matriz2
print(suma)

[[ 6  8]
 [11 13]]


 Indexing, Slicing e Iterating con arrays NumPy

In [73]:
#INDEXING  (índices)
arr = np.array([[1,2,3], 
                [4,5,6],
                [7,8,9]])
print(arr[0,1])  #Devuelve el elemento en la fila 0, columna 1

2


In [74]:
#SLICING  (corte)
print(arr[:, 1])   #Todas las filas, columna 1
print(arr[0:2, 0]) #Filas 0 a 1, columna 0

[2 5 8]
[1 4]


In [69]:
#ITERATING  (recorrido)
for row in arr:
    print(row)
    
for value in np.nditer(arr):
    print(value)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [62]:
#Extrae la fila 2 de una matriz 4x4
fila_2 = matrix4x4[1] #Index 1
print("La fila 2 es: ", fila_2)

La fila 2 es:  [8 6 3 0]


In [ ]:
#Cambiar todos los valores de la columna 0 por 9
arr[:,1] = 99 
print(arr)

[[ 1 99  3]
 [ 4 99  6]
 [ 7 99  9]]


In [64]:
array = np.array([[1, 6, 3],
                  [7, 2, 8],
                  [4, 9, 0]])

mayores_a_5 = array[array > 5]
print(mayores_a_5) 
type(mayores_a_5) #Regresa un array de numpy con los valores

[6 7 8 9]


numpy.ndarray

STACKING (UNIR ARRAYS)

In [ ]:
#Unir verticalmente (uno debajo del otro)
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

v = np.vstack((a,b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [67]:
#Unir horizontalmente (uno al lado del otro)
h = np.hstack((a,b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


SPLITTING (DIVIDIR ARRAYS)

In [78]:
#Dividir verticalmente
arr = np.array([[1,2,3,4], 
                [5,6,7,8]])
v1, v2 = np.vsplit(arr, 2)
print("Parte 1", v1)
print("Parte 2", v2)

Parte 1 [[1 2 3 4]]
Parte 2 [[5 6 7 8]]


In [82]:
h1, h2 = np.hsplit(arr, 2)
print(h1)

[[1 2]
 [5 6]]


In [93]:
#Dividir una matriz 6x2 en tres submatrices
matriz6x2= np.array([[4,5],
                     [3,1],
                     [7,9],
                     [1,4],
                     [0,0],
                     [8,3]])

part1, part2, part3 = np.vsplit(matriz6x2, 3)

print(part1)
print(part2)
print(part3)

[[4 5]
 [3 1]]
[[7 9]
 [1 4]]
[[0 0]
 [8 3]]
